button:
  -
    name: "Private Text"
    sub_button:
      -
        type: "view"
        name: "Send Text"
        url: "http://128.54.9.213/msgs/auth"
      -
        type: "click"
        name: "View Replies"
        key: "VIEW_REPLY"
      - 
        type: "click"
        name: "Help"
        key: "HELP"
